/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

/**
 *
 * @author LENOVO
 */
public class kalkulator extends javax.swing.JFrame {
    String angka;
    Double jumlah, bil1, bil2;
    int pilih;
         
    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
        angka ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tampilanteks = new javax.swing.JTextField();
        BTNHAPUS = new javax.swing.JButton();
        ANGKA1 = new javax.swing.JButton();
        ANGKA4 = new javax.swing.JButton();
        ANGKA7 = new javax.swing.JButton();
        ANGKA2 = new javax.swing.JButton();
        ANGKA5 = new javax.swing.JButton();
        ANGKA8 = new javax.swing.JButton();
        ANGKA3 = new javax.swing.JButton();
        ANGKA6 = new javax.swing.JButton();
        ANGKA9 = new javax.swing.JButton();
        BTNKURANG = new javax.swing.JButton();
        BTNTAMBAH = new javax.swing.JButton();
        BTNBAGI = new javax.swing.JButton();
        BTNKALI = new javax.swing.JButton();
        BTNHASIL = new javax.swing.JButton();
        BTNTITIK = new javax.swing.JButton();
        ANGKA0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        tampilanteks.setBackground(new java.awt.Color(153, 153, 153));
        tampilanteks.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tampilanteks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilanteksActionPerformed(evt);
            }
        });

        BTNHAPUS.setBackground(new java.awt.Color(255, 0, 0));
        BTNHAPUS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNHAPUS.setText("c");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        ANGKA1.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA1.setText("1");
        ANGKA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA1ActionPerformed(evt);
            }
        });

        ANGKA4.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA4.setText("4");
        ANGKA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA4ActionPerformed(evt);
            }
        });

        ANGKA7.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA7.setText("7");
        ANGKA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA7ActionPerformed(evt);
            }
        });

        ANGKA2.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA2.setText("2");
        ANGKA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA2ActionPerformed(evt);
            }
        });

        ANGKA5.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA5.setText("5");
        ANGKA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA5ActionPerformed(evt);
            }
        });

        ANGKA8.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA8.setText("8");
        ANGKA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA8ActionPerformed(evt);
            }
        });

        ANGKA3.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA3.setText("3");
        ANGKA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA3ActionPerformed(evt);
            }
        });

        ANGKA6.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA6.setText("6");
        ANGKA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA6ActionPerformed(evt);
            }
        });

        ANGKA9.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA9.setText("9");
        ANGKA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA9ActionPerformed(evt);
            }
        });

        BTNKURANG.setBackground(new java.awt.Color(255, 255, 51));
        BTNKURANG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNKURANG.setText("-");
        BTNKURANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKURANGActionPerformed(evt);
            }
        });

        BTNTAMBAH.setBackground(new java.awt.Color(255, 255, 51));
        BTNTAMBAH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNTAMBAH.setText("+");
        BTNTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTAMBAHActionPerformed(evt);
            }
        });

        BTNBAGI.setBackground(new java.awt.Color(255, 255, 51));
        BTNBAGI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNBAGI.setText("/");
        BTNBAGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBAGIActionPerformed(evt);
            }
        });

        BTNKALI.setBackground(new java.awt.Color(255, 255, 51));
        BTNKALI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNKALI.setText("*");
        BTNKALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKALIActionPerformed(evt);
            }
        });

        BTNHASIL.setBackground(new java.awt.Color(255, 0, 0));
        BTNHASIL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNHASIL.setText("=");
        BTNHASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHASILActionPerformed(evt);
            }
        });

        BTNTITIK.setBackground(new java.awt.Color(153, 153, 153));
        BTNTITIK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTNTITIK.setText(".");
        BTNTITIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTITIKActionPerformed(evt);
            }
        });

        ANGKA0.setBackground(new java.awt.Color(153, 153, 153));
        ANGKA0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANGKA0.setText("0");
        ANGKA0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tampilanteks, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNKURANG, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ANGKA1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ANGKA2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ANGKA3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ANGKA0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ANGKA7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ANGKA8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ANGKA9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNKALI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTNTITIK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNHASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(ANGKA4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ANGKA5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(ANGKA6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNBAGI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilanteks, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNKURANG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ANGKA1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ANGKA2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ANGKA3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBAGI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNKALI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTITIK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNHASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ANGKA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA5ActionPerformed
       angka +="5";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA5ActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
        tampilanteks.setText(angka);
        bil1 = 0.0;
        bil2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_BTNHAPUSActionPerformed

    private void ANGKA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA1ActionPerformed
        angka +="1";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA1ActionPerformed

    private void ANGKA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA2ActionPerformed
        angka +="2";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA2ActionPerformed

    private void ANGKA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA3ActionPerformed
        angka +="3";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA3ActionPerformed

    private void ANGKA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA4ActionPerformed
        angka +="4";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA4ActionPerformed

    private void ANGKA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA6ActionPerformed
        angka +="6";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA6ActionPerformed

    private void ANGKA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA7ActionPerformed
        angka +="7";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA7ActionPerformed

    private void ANGKA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA8ActionPerformed
        angka +="8";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA8ActionPerformed

    private void ANGKA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA9ActionPerformed
       angka +="9";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA9ActionPerformed

    private void ANGKA0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA0ActionPerformed
        angka +="0";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_ANGKA0ActionPerformed

    private void BTNKURANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKURANGActionPerformed
        bil1 = Double.parseDouble(angka);
        tampilanteks.setText("-");
        angka = "";
        pilih=1;
    }//GEN-LAST:event_BTNKURANGActionPerformed

    private void BTNTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTAMBAHActionPerformed
       bil1 = Double.parseDouble(angka);
        tampilanteks.setText("+");
        angka = "";
        pilih=2;
    }//GEN-LAST:event_BTNTAMBAHActionPerformed

    private void BTNBAGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBAGIActionPerformed
        bil1 = Double.parseDouble(angka);
        tampilanteks.setText("/");
        angka = "";
        pilih=3;
    }//GEN-LAST:event_BTNBAGIActionPerformed

    private void BTNKALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKALIActionPerformed
        bil1 = Double.parseDouble(angka);
        tampilanteks.setText("*");
        angka = "";
        pilih=4;
    }//GEN-LAST:event_BTNKALIActionPerformed

    private void BTNHASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHASILActionPerformed
        // TODO add your handling code here:
        switch (pilih){
            case 1:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1-bil2;
                angka = Double.toString(jumlah);
                tampilanteks.setText(angka);
                break;
            case 2:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1+bil2;
                angka = Double.toString(jumlah);
                tampilanteks.setText(angka);
                break;
            case 3:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1/bil2;
                angka = Double.toString(jumlah);
                tampilanteks.setText(angka);
                break;
            case 4:
                bil2 = Double.parseDouble(angka);
                jumlah = bil1*bil2;
                angka = Double.toString(jumlah);
                tampilanteks.setText(angka);
                break;
            default:
                break;
                
        }
    }//GEN-LAST:event_BTNHASILActionPerformed

    private void BTNTITIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTITIKActionPerformed
        angka +=",";
       tampilanteks.setText(angka);
    }//GEN-LAST:event_BTNTITIKActionPerformed

    private void tampilanteksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilanteksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilanteksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANGKA0;
    private javax.swing.JButton ANGKA1;
    private javax.swing.JButton ANGKA2;
    private javax.swing.JButton ANGKA3;
    private javax.swing.JButton ANGKA4;
    private javax.swing.JButton ANGKA5;
    private javax.swing.JButton ANGKA6;
    private javax.swing.JButton ANGKA7;
    private javax.swing.JButton ANGKA8;
    private javax.swing.JButton ANGKA9;
    private javax.swing.JButton BTNBAGI;
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton BTNHASIL;
    private javax.swing.JButton BTNKALI;
    private javax.swing.JButton BTNKURANG;
    private javax.swing.JButton BTNTAMBAH;
    private javax.swing.JButton BTNTITIK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tampilanteks;
    // End of variables declaration//GEN-END:variables
}
